### ISSUE TITLE
Why Node in TypeScript?

### ISSUE THREAD

**Issue by iammelvin** [DavideViolante/Angular-Full-Stack#139]
You have written backend using typescript and compiled them to javascript is it a good practice why did you do so ? Since you want that to be object oriented ?

**Comment by DavideViolante** [comment]
I think you should read some articles from those results:
- https://www.google.com/search?q=typescript+vs+javascript
- https://www.google.it/search?q=typescript+advantages
I used it because you have only 1 language both frontend and backend, plus all the benefits listed above.

An old version of this project used JS in backend and TS in frontend.

**Comment by iammelvin** [comment]
Yeah i am new to nodejs just now saw that microsoft has an official seed project with typescript and node anyways thanks for the reply i started angular 4 in ts so this should be super easy for me now 💃 💃
