### ISSUE TITLE
Error while deploying to Heroku

### ISSUE THREAD

**Issue by Mean563** [DavideViolante/Angular-Full-Stack#148]
@DavideViolante , I am getting Error, while deploying the application in Heroku followed steps below like you suggested, but i am getting Error 

 ```
ERROR in ./node_modules/angular2-jwt/angular2-jwt.js
remote:        Module not found: Error: Can't resolve 'tslib' in '/tmp/build_7a2243aa5752b65759f4e9ca80a33577/node_modules/angular2-jwt'
remote:        resolve 'tslib' in '/tmp/build_7a2243aa5752b65759f4e9ca80a33577/node_modules/angular2-jwt' 
```

**Comment by Mean563** [comment]
@DavideViolante  any help from you, if possible?

Thanks in advance !!!

**Comment by DavideViolante** [comment]
I don't know what is causing this, I'm sorry. I cannot find anything online too.

**Comment by dougal83** [comment]
Is this linked to the following warning after running 'npm i'?

`npm WARN angular2-jwt@0.2.3 requires a peer of @angular/core@^2.0.0||^4.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by Mean563** [comment]
@dougal83 ,   I was follow below steps but I am getting above error 

[](https://github.com/DavideViolante/Angular-Full-Stack#deploy-heroku)

**Comment by dhruv217** [comment]
@DavideViolante, the error is due to the -aot & -prod tag in "ng build -aot -prod" in "postinstall" script removing those will easily get it to run on heroku.
Also, I changed the npm production variable "heroku config:set NPM_CONFIG_PRODUCTION=false" in heroku to false as you see, so that I wouldn't have to move devDependencies like "@angular/cli" to dependencies, but this is totally up to the users preferance.
And thanks for the awesome repo saved me a ton of time with a personal project.

**Comment by Mean563** [comment]
Hi @dhruv217 , could you please help me what i need to do successfully deploy on heroku , if possible for you.

Thanks in advance !!

**Comment by dhruv217** [comment]
@Mean563 Follow the Deploy tutorial in readme. But instead of step 9, there are two things you can do. 
1) this is necessary.
 you need to change the package.json for script "postinstall"
change it from:-
"postinstall": "tsc -p server && ng build -aot -prod" //mentioned in the readme.
change it to:-
"postinstall": "tsc -p server && ng build"

2) this is optional 
if you chose you can also set the heroku server config to install devDependencies of your project too(by running the command mentioned in my previous comment).
In which case you don't need to copy devDependencies like angular/cli to dependencies.

Follow the rest of tutorial the same way.

**Comment by Mean563** [comment]
Yeah, Working fine Thanks for your help @DavideViolante  and @dougal83  and @dougal83
