### ISSUE TITLE
concurrently execute command in package.json will delete folder "dist"

### ISSUE THREAD

**Issue by Alex-Lin** [DavideViolante/Angular-Full-Stack#35]
i use "ng serve -pc proxy.conf.json --open" "sleep 10 && tsc -w -p server" currently

has any tricks to guarantee the command execution sequence.

**Comment by DavideViolante** [comment]
The dist folder is automatically deleted by the `ng serve` command: https://github.com/angular/angular-cli/pull/4293
I hate that too.

**Comment by avbentem** [comment]
Just for your information: note that [since 1.1.0-rc.0](https://github.com/angular/angular-cli/issues/4366#issuecomment-302539322) `ng serve` supports `--delete-output-path=false`, which suppresses deletion of `dist` (or whatever folder is configured in `.angular-cli.json`, or on the command line using `ng serve --output-path=...`).
