### ISSUE TITLE
Where is dist/public?

### ISSUE THREAD

**Issue by antonyRoberts** [DavideViolante/Angular-Full-Stack#40]
If I build with ```npm run dev``` The program compiles and runs but there is no dist/public folder.
![whereispublic](https://cloud.githubusercontent.com/assets/19535379/24920519/85eabb80-1eb5-11e7-8ad6-6a6d714c200a.png)
Building with ```ng build --prod``` compiles fine but still no idea where dist/public is

**Comment by antonyRoberts** [comment]
This ends up happening on [fix(serve): delete dist on serve](https://github.com/angular/angular-cli/pull/4293) and I see that you've referenced this issue, so I'll close

**Comment by DavideViolante** [comment]
When using `npm run dev` it execute `ng serve`. Since this https://github.com/angular/angular-cli/pull/4293 the dist folder is automatically deleted when using `ng serve` and the files are being loaded from memory. Use `ng build` to create dist folder, then run the app using this sequence:
1. `npm run predev`
2. `mongod`
3. `npm start`

**Comment by antonyRoberts** [comment]
Thanks @DavideViolante I found ```ng build ``` works to, and mongo is already running as a service, would you happen to know how to change port 4200, do we have to eject ng-cli to do it?

**Comment by DavideViolante** [comment]
You can change the 4200 from `.angular-cli.json` file (see here https://github.com/angular/angular-cli/wiki/angular-cli)
You can change the 3000 backend port from app.ts file (remember to change to proxy.conf.json too)
