### ISSUE TITLE
Question regarding /server linting

### ISSUE THREAD

**Issue by zbagley** [DavideViolante/Angular-Full-Stack#61]
Getting more familiar with this codebase (which is the best MEAN boilerplate I've found btw, thank you for that), and I'm not seeing any linting for the server portion/express app. Am I missing something obvious?

If not, is there a specific reason why you chose to only lint /client? Also, would you be interested in receiving a PR with a lint set up for /server?

**Comment by DavideViolante** [comment]
Actually I never noticed it because I've TSLint extension installed on VS Code so I get noticed by any linting error while coding, also on server side.
I think you are right about the `ng lint` command. That command it's included in Angular CLI, so it verifies only client side code. I don't know if that command can be extended to server folder too, but I don't think so. 
I just added another command to verify server side code (I didn't think it would be enough 1 line). Tell me if this is what you wanted to do. https://github.com/DavideViolante/Angular-Full-Stack/commit/45edf46913048d600a3645c2d53403741a8456f8
Keep in mind that I'm trying to keep this project as simple as possible.

**Comment by zbagley** [comment]
This is perfect. The main reason was for static testing on a Jenkins server, and wanting to make sure that in the future people keep up with best practices.
